// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPf-_YStclHJxVjEynht1FlgfUcEDUw9I',
    appId: '1:189006121648:web:8b7bd2fe8dfd6d0736c975',
    messagingSenderId: '189006121648',
    projectId: 'ezycart-a1ba4',
    authDomain: 'ezycart-a1ba4.firebaseapp.com',
    storageBucket: 'ezycart-a1ba4.firebasestorage.app',
    measurementId: 'G-BXWPEX9R1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBubZ4k3MdO8f0DW7dbCUOHmInJs_CoXzk',
    appId: '1:189006121648:android:39a6f91f74fb12b836c975',
    messagingSenderId: '189006121648',
    projectId: 'ezycart-a1ba4',
    storageBucket: 'ezycart-a1ba4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALZPF50Lopifeq24k7oGMV9K24MyoMrq8',
    appId: '1:189006121648:ios:011c4416b1c31a0036c975',
    messagingSenderId: '189006121648',
    projectId: 'ezycart-a1ba4',
    storageBucket: 'ezycart-a1ba4.firebasestorage.app',
    iosClientId: '189006121648-utdbc0qjm37n87vu4750sgk838kj9j3c.apps.googleusercontent.com',
    iosBundleId: 'com.example.ezycart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALZPF50Lopifeq24k7oGMV9K24MyoMrq8',
    appId: '1:189006121648:ios:011c4416b1c31a0036c975',
    messagingSenderId: '189006121648',
    projectId: 'ezycart-a1ba4',
    storageBucket: 'ezycart-a1ba4.firebasestorage.app',
    iosClientId: '189006121648-utdbc0qjm37n87vu4750sgk838kj9j3c.apps.googleusercontent.com',
    iosBundleId: 'com.example.ezycart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPf-_YStclHJxVjEynht1FlgfUcEDUw9I',
    appId: '1:189006121648:web:2b59ccb1aae904cb36c975',
    messagingSenderId: '189006121648',
    projectId: 'ezycart-a1ba4',
    authDomain: 'ezycart-a1ba4.firebaseapp.com',
    storageBucket: 'ezycart-a1ba4.firebasestorage.app',
    measurementId: 'G-9NTX9B7TJ5',
  );
}
